package com.applitools.eyes.selenium;
import com.applitools.eyes.BatchInfo;
import com.applitools.eyes.ProxySettings;
import com.applitools.eyes.StdoutLogHandler;
import com.applitools.eyes.selenium.fluent.Target;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class BatchSequenceName {
    // Generated by Selenium IDE

        private Eyes eyes;
        @Test
        public void styleGuide() {
            eyes = new Eyes();
            eyes.setLogHandler(new StdoutLogHandler());
            BatchInfo batch = new BatchInfo("BatchSequnceName Batch");
            Configuration configuration = new Configuration();
            configuration.setProxy(new ProxySettings("http://127.0.0.1", 8888, null, null));
            configuration.setServerUrl("https://testeyes.applitools.com/");
            configuration.setApiKey("ACrb4NqtyPFtin75ambUgsJ67UV3twmQpfiBoq1050AIU110");
            eyes.setConfiguration(configuration);
            eyes.setBatch(batch);
            String batchSequenceName = eyes.getBatch().getBatchSequenceName();
            if(batch == null) throw new Error();
            WebDriver driver = new ChromeDriver();
            batch.setBatchSequenceName("new batch sequence");
            eyes.open(driver, "Java Eyes SDK", "BatchSequnceName Batch");
            driver.get("http://applitools.github.io/demo/TestPages/VisualGridTestPage/index.html");

            eyes.check(Target.window().fully());

            eyes.close();
        }
    }

