package com.applitools.eyes.selenium;

import com.applitools.eyes.BatchInfo;
import com.applitools.eyes.ProxySettings;
import com.applitools.eyes.StdoutLogHandler;
import com.applitools.eyes.selenium.fluent.Target;
import com.applitools.eyes.selenium.rendering.VisualGridEyes;
import com.applitools.utils.GeneralUtils;
import com.applitools.utils.Iso8610CalendarDeserializer;
import com.applitools.utils.Iso8610CalendarSerializer;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

import java.io.IOException;

public class TestBatchSequenceName {
    // Generated by Selenium IDE

    private Eyes eyes;

    @Test
    public void test() {
        ObjectMapper objectMapper = new ObjectMapper();
        String json1 = null;
        String json2 = null;
        try {
            json1 = GeneralUtils.readToEnd(TestBatchSequenceName.class.getResourceAsStream("/batchSequenceName1.json"));
            json2 = GeneralUtils.readToEnd(TestBatchSequenceName.class.getResourceAsStream("/batchSequenceName2.json"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        eyes = new Eyes();
        BatchInfo batch = new BatchInfo("BatchSequnceName Batch");
        batch.setId("6e712b7a-61fd-45d1-87a3-c8af9df8a3d6");
        Configuration configuration = new Configuration();
//        configuration.setProxy(new ProxySettings("http://127.0.0.1", 8888, null, null));

        BatchInfo obj = null;
        BatchInfo obj2 = null;
        try {
            obj = objectMapper.readValue(json1, BatchInfo.class);
            obj2 = objectMapper.readValue(json2, BatchInfo.class);
        } catch (IOException e) {
            e.printStackTrace();
        }

        eyes.setConfiguration(configuration);
        eyes.setBatch(batch);
        String batchSequenceName = eyes.getBatch().getSequenceName();
        if (batchSequenceName == null) throw new Error();
        WebDriver driver = new ChromeDriver();
        try {
            eyes.open(driver, "Java Eyes SDK", "BatchSequnceName Batch");

            eyes.check(Target.window());

            eyes.close(false);

            batch.setStartedAt("2019-06-04T10:27:15Z");


            if(!batch.equals(obj)) throw new Error("Batches(1) not equal");

            batch.setSequenceName("newSequenceName by setter");

            batch.setId("ljndsfknqe12e2qefjh");

            eyes.open(driver, "Java Eyes SDK", "BatchSequnceName Batch");

            eyes.check(Target.window());

            eyes.close(false);

            if(!batch.equals(obj2)) throw new Error("Batches(2) not equal");

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            driver.quit();
        }
    }

}

